## Task 2 :SQL for Data Extraction  and Analysis

### Objective

The objective of this task is to use SQL queries for data extraction and business analysis by integrating SQLite with Python in Jupyter Notebook.

## Import Required libraries

In [1]:
# import Pandas for data manipulation and SQLite3 for database operations

In [2]:
import pandas as pd 
import sqlite3

In [3]:
# Load Cleaned Dataset

In [4]:
df = pd.read_csv("../data/SampleSuperstore_Cleaned.csv")

In [5]:
# Display the first 5 rows of the dataset

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

## Create SQLite Database Connection

In [7]:
# Create a connection to a SQLite database

In [8]:
conn = sqlite3.connect("superstore.db")

## Import Dataset into SQLite Database

In [9]:
# Store the Dataframe as a table in the SQLite Database

In [10]:
df.to_sql("superstore",conn,if_exists = "replace",index = False)

8827

In [11]:
# Check whether the table was successfully crated

In [12]:
query = "SELECT name FROM sqlite_master WHERE type = 'table';"
pd.read_sql(query,conn)

         name
0   customers
1      orders
2  superstore

## View First 5 Records Using SQL

In [13]:
# Retrieve the first 5 rows from the database table

In [14]:
query = """
SELECT * 
FROM superstore
LIMIT 5 ;
"""
pd.read_sql(query , conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

## SQL Fundamentals

# SELECT  
Used to choose which columns you want to see.

In [15]:
query = """
SELECT "Customer Name",
        Sales
FROM superstore;
"""
pd.read_sql(query, conn)

         Customer Name    Sales
0          Claire Gute  261.960
1      Darrin Van Huff   14.620
2       Sean O'Donnell   22.368
3      Brosina Hoffman   48.860
4      Brosina Hoffman    7.280
...                ...      ...
8822  Tom Boeckenhauer   25.248
8823       Dave Brooks   91.960
8824       Dave Brooks  258.576
8825       Dave Brooks   29.600
8826      Chris Cortes  243.160

[8827 rows x 2 columns]

# Insight:
 The SELECT statement is used to retrieve specific columns from the dataset.
 It helps focus on relevant information instead of viewing the entire table.

# WHERE
Filters data based on a condition

In [16]:
query = """
SELECT *
FROM superstore
WHERE Category = 'Technology';
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,20,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
1,27,CA-2016-121755,2016-01-16,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741
2,41,CA-2015-117415,2015-12-27,2015-12-31,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.168,4,0.2,41.7564
3,42,CA-2017-120999,2017-09-10,2017-09-15,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,...,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,45,CA-2016-118255,2016-03-11,2016-03-13,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,...,55122,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.980,2,0.0,19.7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,9984,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.980,2,0.0,27.4344
1443,9987,CA-2016-125794,2016-09-29,2016-10-03,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208
1444,9988,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0.0,28.7964
1445,9989,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
1446,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932

# Insight:
 The WHERE clause filters records based on specific conditions.
 It helps analyze only the required subset of data, such as a product category or region.

# ORDER BY 
Sorts Data

In [17]:
query = """
SELECT "Customer Name",
       Sales
FROM superstore
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

         Customer Name    Sales
0      Cynthia Arntzen  498.260
1         Tamara Chand  498.000
2        Justin Ritter  497.940
3      Muhammed Yedwab  497.610
4        Bruce Stewart  496.860
...                ...      ...
8822     Henry Goldwyn    0.876
8823     Jas O'Carroll    0.852
8824       Ken Brennan    0.836
8825    Roland Schwarz    0.556
8826  Zuschuss Carroll    0.444

[8827 rows x 2 columns]

# Insight:
 ORDER BY arranges data in ascending or descending order.
 It helps identify top-performing customers, products, or regions.

# LIMIT
Restricts the number of rows returned

In [18]:
query = """
SELECT *
FROM superstore
LIMIT 5;
"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

# Insight:
 LIMIT restricts the number of records returned by a query.
 It is useful for quickly inspecting sample data without loading the entire dataset.

# GROUP BY
Helps summarize the data

In [19]:
query = """ 
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category 
ORDER BY Total_Sales DESC;
"""
pd.read_sql(query,conn)

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

# Insight:
 GROUP BY combines records with similar values into groups.
 It helps summarize data and calculate metrics such as total sales,
 average profit, and customer counts.

 ## HAVING Clause

In [20]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
HAVING SUM(Sales) > 700000;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [Category, Total_Sales]
Index: []

# Insight:
 HAVING filters grouped results after aggregation.
 It helps identify groups that meet specific conditions,
 such as categories with high sales or profit.

 # INNER JOIN

In [21]:
# Create a sample customer table and store it in the SQLite database.

In [22]:
customer_data = {
    "Customer_ID": ["C1", "C2", "C3"],
    "Customer_Name": ["Robert", "Nick", "John"]
}

customer_df = pd.DataFrame(customer_data)
customer_df.to_sql("customers", conn, if_exists="replace", index=False)

3

In [23]:
order_data = {
    "Customer_ID": ["C1", "C2", "C3"],
    "Sales": [500, 800, 600]
}

order_df = pd.DataFrame(order_data)
order_df.to_sql("orders", conn, if_exists="replace", index=False)

3

In [24]:
query = """
SELECT customers.Customer_Name,
       orders.Sales
FROM customers
INNER JOIN orders
ON customers.Customer_ID = orders.Customer_ID;
"""

pd.read_sql(query, conn)

  Customer_Name  Sales
0        Robert    500
1          Nick    800
2          John    600

# Insight:
 INNER JOIN combines matching records from two tables.
It helps integrate related information stored across multiple tables.

# LEFT JOIN

In [25]:
# left join returns all records from the left table and matching from the right table

In [26]:
query = """
SELECT customers.Customer_Name,
       orders.Sales
FROM customers
LEFT JOIN orders
ON customers.Customer_ID = orders.Customer_ID;
"""

pd.read_sql(query, conn)

  Customer_Name  Sales
0        Robert    500
1          Nick    800
2          John    600

# Insight:
 LEFT JOIN returns all records from the left table and matching records
 from the right table. It helps identify missing or unmatched data.

 ## RIGHT JOIN

In [27]:
# Right join returns all records from the right table and matching records from the left table

In [28]:
query = """
SELECT customers.Customer_Name,
       orders.Sales
FROM orders
LEFT JOIN customers
ON orders.Customer_ID = customers.Customer_ID;
"""

pd.read_sql(query, conn)

  Customer_Name  Sales
0        Robert    500
1          Nick    800
2          John    600

# Insight:
 RIGHT JOIN returns all records from the right table and matching records
 from the left table. It is useful when all records from the right table
 need to be preserved.

 ## FULL OUTER JOIN

In [29]:
# Full Outer JOin returns all records from both tables

In [30]:
query = """
SELECT customers.Customer_Name,
       orders.Sales
FROM customers
LEFT JOIN orders
ON customers.Customer_ID = orders.Customer_ID

UNION

SELECT customers.Customer_Name,
       orders.Sales
FROM orders
LEFT JOIN customers
ON orders.Customer_ID = customers.Customer_ID;
"""

pd.read_sql(query, conn)

  Customer_Name  Sales
0          John    600
1          Nick    800
2        Robert    500

# Insight:
 FULL OUTER JOIN returns all records from both tables,
 whether matching or not. It provides a complete view of the data.

 # Overall Insight:
SQL Fundamentals enabled efficient extraction, filtering, sorting, grouping, and combining of data. These operations form the foundation of data analysis and support business decision-making through structured data exploration.

## Total Sales by Category

In [31]:
# Calculate total Sales by each category

In [32]:
query = """ 
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category 
ORDER BY Total_Sales DESC;
"""
pd.read_sql(query,conn)

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

## Average Sales By Category

In [33]:
# Calculate Average Sales by each category

In [34]:
query = """
SELECT Category,
       AVG(Sales) AS Average_Sales
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Average_Sales
0        Furniture     149.865598
1  Office Supplies      59.976424
2       Technology     157.854425

## Total Profit by Category

In [35]:
# Calculate total profit generated by each category

In [36]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category 
ORDER BY Total_Profit DESC;
"""
pd.read_sql(query,conn)

          Category  Total_Profit
0  Office Supplies    66179.5379
1       Technology    35385.4240
2        Furniture    -2714.5353

##  Average Profit By Category

In [37]:
query = """
SELECT Category,
       AVG(Profit) AS Average_Profit
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Average_Profit
0        Furniture       -1.641194
1  Office Supplies       11.557726
2       Technology       24.454336

In [38]:
# Display the structure of the superstore table,
# including column names, data types, and column information.

In [39]:
pd.read_sql("PRAGMA table_info(superstore);",conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [40]:
# Display the 10 orders with the highest sales

In [41]:
query = """
SELECT "Order ID",
       "Customer Name",
       Category,
       Sales
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

         Order ID        Customer Name         Category    Sales
0  CA-2017-145653      Cynthia Arntzen        Furniture  498.260
1  CA-2014-153087         Tamara Chand       Technology  498.000
2  CA-2017-159506        Justin Ritter  Office Supplies  497.940
3  CA-2014-118976      Muhammed Yedwab  Office Supplies  497.610
4  CA-2016-156748        Bruce Stewart  Office Supplies  496.860
5  US-2016-126893         Carol Triggs       Technology  494.982
6  US-2017-162670       Monica Federle       Technology  494.970
7  CA-2015-163237       Eudokia Martin       Technology  494.970
8  US-2016-100720  Chloris Kastensmidt       Technology  494.376
9  CA-2015-157770             Rob Dowd       Technology  494.376

In [42]:
# Retrieve the schema of the superstore table
# to view column names, data types, and table structure.

In [43]:
query = """
PRAGMA table_info(superstore);
"""
pd.read_sql(query, conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [44]:
# Retrieve the first 10 records from the Technology category

In [45]:
query = """
SELECT "Customer Name",
       Category,
       Sales
FROM superstore
WHERE Category = 'Technology'
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name    Category    Sales
0  Zuschuss Donatelli  Technology  213.480
1       Eric Hoffmann  Technology   90.570
2        Steve Nguyen  Technology  371.168
3      Linda Cazamias  Technology  147.168
4       Odella Nelson  Technology   45.980
5      Lena Hernandez  Technology   45.000
6      Lena Hernandez  Technology   21.800
7     Ted Butterfield  Technology   30.000
8        Kunst Miller  Technology   13.980
9       Brendan Sweed  Technology  167.968

In [46]:
# Customers from Furniture Category

In [47]:
query = """
SELECT "Customer Name",
        Category,
        Sales,
        Profit
FROM superstore
WHERE Category = 'Furniture'
ORDER BY Sales DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

      Customer Name   Category    Sales    Profit
0   Cynthia Arntzen  Furniture  498.260  134.5302
1        Erin Smith  Furniture  493.920  -28.2240
2       Sarah Brown  Furniture  493.430  -70.4900
3    Bill Donatelli  Furniture  492.835  -14.0810
4     Gary Zandusky  Furniture  489.230   41.9340
5   Katrina Willman  Furniture  488.646   86.8704
6      Rick Bensley  Furniture  487.960  146.3880
7        Bruce Geld  Furniture  486.368   36.4776
8  Stewart Visinsky  Furniture  484.704  -84.8232
9    Lena Creighton  Furniture  483.136   54.3528

In [48]:
# Customers from Office Supplies Category

In [49]:
query = """
SELECT "Customer Name",
       Category,
       Sales,
       Profit
FROM superstore
WHERE Category = 'Office Supplies'
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

      Customer Name         Category    Sales    Profit
0     Justin Ritter  Office Supplies  497.940  224.0730
1   Muhammed Yedwab  Office Supplies  497.610  129.3786
2     Bruce Stewart  Office Supplies  496.860   24.8430
3     Maurice Satty  Office Supplies  491.550  240.8595
4  Heather Kirkland  Office Supplies  491.550  240.8595
5     Paul Van Hugh  Office Supplies  490.320  137.2896
6   Shirley Daniels  Office Supplies  489.920    0.0000
7     Jas O'Carroll  Office Supplies  487.984  152.4950
8      Ralph Arnett  Office Supplies  487.984  152.4950
9      Michael Chen  Office Supplies  487.984  152.4950

## Number of Orders by Category

In [50]:
query = """
SELECT Category,
       COUNT(*) AS Total_Orders
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Total_Orders
0        Furniture          1654
1  Office Supplies          5726
2       Technology          1447

## Total Sales by Region

In [51]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0  Central  183440.9134
1     East  232887.4840
2    South  127579.3955
3     West  275810.2625

## Advanced SQL

# Subquery

In [52]:
# A subquery is a query inside another query.
# It helps retrieve data based on the result of another query.

In [53]:
query = """
SELECT "Customer Name",
       Sales
FROM superstore
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM superstore
);
"""

pd.read_sql(query, conn)

           Customer Name    Sales
0            Claire Gute  261.960
1        Brosina Hoffman  114.900
2           Irene Maddox  407.976
3     Zuschuss Donatelli  213.480
4        Tracy Blumstein  124.200
...                  ...      ...
2753          Anne Pryor  437.472
2754          Ryan Crowe   97.980
2755        Ruben Ausman  206.100
2756         Dave Brooks  258.576
2757        Chris Cortes  243.160

[2758 rows x 2 columns]

# Insight:
 This query finds customers whose sales are greater than the average sales.
 Subqueries help compare records against aggregated values such as
 average sales, maximum profit, minimum sales, etc.

## CTE (WITH Clause)

In [54]:
# CTE creates a temporary result set that can be reused in the main query

In [55]:
query = """
WITH CategorySales AS
(
    SELECT Category,
           SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Category
)

SELECT *
FROM CategorySales;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

# Insight:
 Office Supplies generated the highest total sales,
 followed by Furniture and Technology.

## ROW_NUMBER() Function

In [56]:
# Assign a unique row number based on sales ranking

In [57]:
query = """
SELECT "Customer Name",
       Sales,

       ROW_NUMBER() OVER
       (
           ORDER BY Sales DESC
       ) AS Row_Number

FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

         Customer Name    Sales  Row_Number
0      Cynthia Arntzen  498.260           1
1         Tamara Chand  498.000           2
2        Justin Ritter  497.940           3
3      Muhammed Yedwab  497.610           4
4        Bruce Stewart  496.860           5
5         Carol Triggs  494.982           6
6       Monica Federle  494.970           7
7       Eudokia Martin  494.970           8
8  Chloris Kastensmidt  494.376           9
9             Rob Dowd  494.376          10

# Insight:
 ROW_NUMBER() assigns a unique sequential number to each row
 based on the specified sorting order. It is useful for ranking,
 identifying top records, and organizing data in a structured manner.

## RANK() Function

In [58]:
# Rank customers based on sales. Same sales values get the same rank.

In [59]:
query = """
SELECT "Customer Name",
       Sales,

       RANK() OVER
       (
           ORDER BY Sales DESC
       ) AS Sales_Rank

FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

         Customer Name    Sales  Sales_Rank
0      Cynthia Arntzen  498.260           1
1         Tamara Chand  498.000           2
2        Justin Ritter  497.940           3
3      Muhammed Yedwab  497.610           4
4        Bruce Stewart  496.860           5
5         Carol Triggs  494.982           6
6       Monica Federle  494.970           7
7       Eudokia Martin  494.970           7
8  Chloris Kastensmidt  494.376           9
9             Rob Dowd  494.376           9

# Insight:
 RANK() assigns the same rank to records with equal sales values.
 Useful for identifying top performers while handling ties correctly.

## LAG() Function

In [60]:
# LAG() returns the previous row's sales value

In [61]:
query = """
SELECT "Customer Name",
       Sales,

       LAG(Sales)
       OVER
       (
           ORDER BY Sales DESC
       ) AS Previous_Sales

FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

         Customer Name    Sales  Previous_Sales
0      Cynthia Arntzen  498.260             NaN
1         Tamara Chand  498.000         498.260
2        Justin Ritter  497.940         498.000
3      Muhammed Yedwab  497.610         497.940
4        Bruce Stewart  496.860         497.610
5         Carol Triggs  494.982         496.860
6       Monica Federle  494.970         494.982
7       Eudokia Martin  494.970         494.970
8  Chloris Kastensmidt  494.376         494.970
9             Rob Dowd  494.376         494.376

 # Insight:
 LAG() helps compare current sales with the previous sales value.
 Useful for trend analysis and performance comparison.

## LEAD() Function

In [62]:
# LEAD() returns the next row's sales value

In [63]:
query = """
SELECT "Customer Name",
       Sales,

       LEAD(Sales)
       OVER
       (
           ORDER BY Sales DESC
       ) AS Next_Sales

FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

         Customer Name    Sales  Next_Sales
0      Cynthia Arntzen  498.260     498.000
1         Tamara Chand  498.000     497.940
2        Justin Ritter  497.940     497.610
3      Muhammed Yedwab  497.610     496.860
4        Bruce Stewart  496.860     494.982
5         Carol Triggs  494.982     494.970
6       Monica Federle  494.970     494.970
7       Eudokia Martin  494.970     494.376
8  Chloris Kastensmidt  494.376     494.376
9             Rob Dowd  494.376     493.920

# Insight:
 LEAD() helps compare current sales with the next sales value.
 Useful for identifying changes between consecutive records.

## VIEW (Reusable Query)

In [64]:
# A VIEW is a virtual table created from a SQL query.
# It stores the query logic and can be reused like a normal table.

In [65]:
# Create View

In [66]:
query = """
DROP VIEW IF EXISTS High_Sales;
"""

conn.execute(query)

In [67]:
query = """
CREATE VIEW High_Sales AS

SELECT "Customer Name",
       Category,
       Sales

FROM superstore

WHERE Sales > 400;
"""

conn.execute(query)

In [68]:
# Retrieve all records from the High_Sales view.
# This view contains customers whose sales are greater than 400.

In [69]:
query = """
SELECT *
FROM High_Sales;
"""

pd.read_sql(query, conn)

       Customer Name         Category    Sales
0       Irene Maddox  Office Supplies  407.976
1        Dave Brooks        Furniture  457.568
2     David Kendrick       Technology  408.744
3    Laurel Elliston       Technology  444.768
4    Victoria Wilson        Furniture  452.450
..               ...              ...      ...
283       Dan Lawera       Technology  479.976
284       Dan Lawera        Furniture  483.136
285    Sally Hughsby        Furniture  403.560
286        Liz Preis        Furniture  466.320
287       Anne Pryor  Office Supplies  437.472

[288 rows x 3 columns]

# Insight:
 The High_Sales view contains customers whose sales exceed 400.
 Views help simplify complex queries and improve reusability.

## Python + SQL Integration

## Business Question 1: Top 5 Products by Sales

In [70]:
query = """
SELECT "Product Name",
       Sales
FROM superstore
ORDER BY Sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                        Product Name   Sales
0     Harbour Creations 67200 Series Stacking Chairs  498.26
1                  Enermax Acrylux Wireless Keyboard  498.00
2           GBC DocuBind P100 Manual Binding Machine  497.94
3  Recycled Steel Personal File for Standard File...  497.61
4          Sensible Storage WireTech Storage Systems  496.86

# Insight:
 These are the products generating the highest sales revenue.
 Identifying top-selling products helps businesses focus on
 profitable inventory and marketing strategies.

## Business Question 2: Monthly Sales Trend

In [71]:
# Calculate total sales for each month

In [72]:
query = """
SELECT SUBSTR("Order Date",6,2) AS Month,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

   Month  Total_Sales
0     01   31911.0090
1     02   27949.8704
2     03   60351.2904
3     04   53156.2521
4     05   58021.9144
5     06   61065.0348
6     07   61027.8890
7     08   56371.0245
8     09  107526.8743
9     10   66334.0502
10    11  117834.1100
11    12  118168.7363

# Insight:
 Monthly sales trends help identify seasonal patterns
 and peak sales periods throughout the year.

## Business Question 3: Customer Segment Wise Sales

In [73]:
# Calculate total sales by customer segment

In [74]:
query = """
SELECT Segment,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Segment;
"""

pd.read_sql(query, conn)

       Segment  Total_Sales
0     Consumer  437711.0838
1    Corporate  240011.9418
2  Home Office  141995.0298

# Insight:
 This analysis shows which customer segment
 contributes the most revenue.

## Business Question 4: Region Wise Profit

In [75]:
# Calculate total profit generated in each region

In [76]:
query = """
SELECT Region,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Region
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Profit
0     West    45885.5132
1     East    28025.6875
2    South    22150.0444
3  Central     2789.1815

# Insight:
 Regions with higher profits can be targeted
 for future business expansion.

## Business Question 5: Top Customers by Sales

In [77]:
# Identify customers with the highest sales

In [78]:
query = """
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

     Customer Name  Total_Sales
0       Paul Prost    4196.9280
1  Laura Armstrong    3751.7980
2     Ken Lonsdale    3371.6910
3         John Lee    3338.3520
4    William Brown    3131.9740
5     Noel Staavos    2964.8230
6      Rick Wilson    2879.8910
7    Sally Hughsby    2865.5995
8     Edward Hooks    2821.2100
9    Arthur Gainer    2806.8510

# Insight:
 These customers contribute significantly
 to overall business revenue.

## Business Question 6: Category Wise Profit

In [79]:
# Calculate profit generated by each category

In [80]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0        Furniture    -2714.5353
1  Office Supplies    66179.5379
2       Technology    35385.4240

# Insight:
 This analysis helps identify the most profitable product category.

## Business Question 7: State Wise Sales

In [81]:
# Calculate total sales for each state

In [82]:
query = """
SELECT State,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California  175475.7375
1      New York   92379.4070
2         Texas   71672.9344
3  Pennsylvania   45628.6270
4    Washington   41245.3560
5          Ohio   37495.3080
6      Illinois   36821.0430
7       Florida   27593.4735
8      Michigan   25737.0760
9       Arizona   20945.1490

# Insight:
 Top-performing states can be targeted for
 additional marketing and sales efforts.

## Business Question 8: Most Profitable Products

In [83]:
# Find products generating the highest profit

In [84]:
query = """
SELECT "Product Name",
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Profit
0                                  Easy-staple paper     1096.0292
1  Dot Matrix Printer Tape Reel Labels, White, 50...      904.4520
2                                         Xerox 1908      799.3944
3                                         Xerox 1945      756.2655
4                                    Staple envelope      751.6290
5                                          Xerox 189      746.5320
6                                         Xerox 1919      729.6220
7                       Enermax Aurora Lite Keyboard      722.1060
8                   Logitech Gaming G510s - Keyboard      676.5204
9  GE 48" Fluorescent Tube, Cool White Energy Sav...      664.8410

# Insight:
 Highly profitable products contribute
 significantly to business growth.

## Business Question 9: Average Discount by Category

In [85]:
# Calculate average discount for each category

In [86]:
query = """
SELECT Category,
       AVG(Discount) AS Avg_Discount
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Avg_Discount
0        Furniture      0.176294
1  Office Supplies      0.159588
2       Technology      0.128404

# Insight:
 Understanding discount patterns helps
 evaluate pricing and promotional strategies.

## Business Question 10: Sales by Ship Mode

In [87]:
# Calculate total sales for each shipping mode

In [88]:
query = """
SELECT "Ship Mode",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Ship Mode";
"""

pd.read_sql(query, conn)

        Ship Mode  Total_Sales
0     First Class  124222.3725
1        Same Day   43995.8350
2    Second Class  161053.4692
3  Standard Class  490446.3787

# Insight:
 This analysis reveals which shipping method
 is associated with the highest sales volume.

# Task Summary

In this task, SQL was integrated with Python using SQLite.

Key SQL concepts practiced:

- SELECT
- WHERE
- ORDER BY
- LIMIT
- GROUP BY
- HAVING
- JOINS
- Subqueries
- CTEs
- Window Functions
- Views

Business insights were extracted using SQL queries executed through Python, demonstrating how SQL can be used for real-world data analysis and decision-making.

## Close Database Connection

In [89]:
# Close the SQLite database connection

In [90]:
conn.close()